image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375

test-docker:
  script:
    - echo "Проверяем Docker..."
    - docker --version
    - echo "Запускаем тестовый контейнер..."
    - docker run --rm alpine:latest echo "Работает!"
    - echo "Успешно завершено"
