echo 'stages:
  - test
  - build
  - deploy

test_stage:
  stage: test
  script:
    - echo "Testing..."

build_stage:
  stage: build
  script:
    - echo "Building..."

deploy_stage:
  stage: deploy
  script:
    - echo "Deploying..."

