image: alpine:latest

stages:
  - test
  - build
  - deploy

test-stage:
  stage: test
  script:
    - echo "Этап 1: Тестирование"
    - echo "ОС: Alpine Linux"
    - echo "Тесты пройдены"

build-stage:
  stage: build
  script:
    - echo "Этап 2: Сборка"
    - echo "Имитация сборки проекта..."
    - echo "Сборка завершена"

deploy-stage:
  stage: deploy
  script:
    - echo "Этап 3: Деплой"
    - echo "Развертывание приложения..."
    - echo "Деплой успешно завершен"
